// Code generated by protoc-gen-go. DO NOT EDIT.
// source: brewery.proto

package brewery_model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Constraint struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Min                  float64  `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64  `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Constraint) Reset()         { *m = Constraint{} }
func (m *Constraint) String() string { return proto.CompactTextString(m) }
func (*Constraint) ProtoMessage()    {}
func (*Constraint) Descriptor() ([]byte, []int) {
	return fileDescriptor_04154031a803dc7e, []int{0}
}

func (m *Constraint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Constraint.Unmarshal(m, b)
}
func (m *Constraint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Constraint.Marshal(b, m, deterministic)
}
func (m *Constraint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Constraint.Merge(m, src)
}
func (m *Constraint) XXX_Size() int {
	return xxx_messageInfo_Constraint.Size(m)
}
func (m *Constraint) XXX_DiscardUnknown() {
	xxx_messageInfo_Constraint.DiscardUnknown(m)
}

var xxx_messageInfo_Constraint proto.InternalMessageInfo

func (m *Constraint) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Constraint) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Constraint) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type ControlScheme struct {
	// Types that are valid to be assigned to Scheme:
	//	*ControlScheme_Boil_
	//	*ControlScheme_Mash_
	//	*ControlScheme_Power_
	Scheme               isControlScheme_Scheme `protobuf_oneof:"scheme"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ControlScheme) Reset()         { *m = ControlScheme{} }
func (m *ControlScheme) String() string { return proto.CompactTextString(m) }
func (*ControlScheme) ProtoMessage()    {}
func (*ControlScheme) Descriptor() ([]byte, []int) {
	return fileDescriptor_04154031a803dc7e, []int{1}
}

func (m *ControlScheme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlScheme.Unmarshal(m, b)
}
func (m *ControlScheme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlScheme.Marshal(b, m, deterministic)
}
func (m *ControlScheme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlScheme.Merge(m, src)
}
func (m *ControlScheme) XXX_Size() int {
	return xxx_messageInfo_ControlScheme.Size(m)
}
func (m *ControlScheme) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlScheme.DiscardUnknown(m)
}

var xxx_messageInfo_ControlScheme proto.InternalMessageInfo

type isControlScheme_Scheme interface {
	isControlScheme_Scheme()
}

type ControlScheme_Boil_ struct {
	Boil *ControlScheme_Boil `protobuf:"bytes,1,opt,name=boil,proto3,oneof"`
}

type ControlScheme_Mash_ struct {
	Mash *ControlScheme_Mash `protobuf:"bytes,2,opt,name=mash,proto3,oneof"`
}

type ControlScheme_Power_ struct {
	Power *ControlScheme_Power `protobuf:"bytes,3,opt,name=power,proto3,oneof"`
}

func (*ControlScheme_Boil_) isControlScheme_Scheme() {}

func (*ControlScheme_Mash_) isControlScheme_Scheme() {}

func (*ControlScheme_Power_) isControlScheme_Scheme() {}

func (m *ControlScheme) GetScheme() isControlScheme_Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

func (m *ControlScheme) GetBoil() *ControlScheme_Boil {
	if x, ok := m.GetScheme().(*ControlScheme_Boil_); ok {
		return x.Boil
	}
	return nil
}

func (m *ControlScheme) GetMash() *ControlScheme_Mash {
	if x, ok := m.GetScheme().(*ControlScheme_Mash_); ok {
		return x.Mash
	}
	return nil
}

func (m *ControlScheme) GetPower() *ControlScheme_Power {
	if x, ok := m.GetScheme().(*ControlScheme_Power_); ok {
		return x.Power
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ControlScheme) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ControlScheme_Boil_)(nil),
		(*ControlScheme_Mash_)(nil),
		(*ControlScheme_Power_)(nil),
	}
}

type ControlScheme_Boil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlScheme_Boil) Reset()         { *m = ControlScheme_Boil{} }
func (m *ControlScheme_Boil) String() string { return proto.CompactTextString(m) }
func (*ControlScheme_Boil) ProtoMessage()    {}
func (*ControlScheme_Boil) Descriptor() ([]byte, []int) {
	return fileDescriptor_04154031a803dc7e, []int{1, 0}
}

func (m *ControlScheme_Boil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlScheme_Boil.Unmarshal(m, b)
}
func (m *ControlScheme_Boil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlScheme_Boil.Marshal(b, m, deterministic)
}
func (m *ControlScheme_Boil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlScheme_Boil.Merge(m, src)
}
func (m *ControlScheme_Boil) XXX_Size() int {
	return xxx_messageInfo_ControlScheme_Boil.Size(m)
}
func (m *ControlScheme_Boil) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlScheme_Boil.DiscardUnknown(m)
}

var xxx_messageInfo_ControlScheme_Boil proto.InternalMessageInfo

type ControlScheme_Mash struct {
	Constraints          []*Constraint `protobuf:"bytes,1,rep,name=constraints,proto3" json:"constraints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ControlScheme_Mash) Reset()         { *m = ControlScheme_Mash{} }
func (m *ControlScheme_Mash) String() string { return proto.CompactTextString(m) }
func (*ControlScheme_Mash) ProtoMessage()    {}
func (*ControlScheme_Mash) Descriptor() ([]byte, []int) {
	return fileDescriptor_04154031a803dc7e, []int{1, 1}
}

func (m *ControlScheme_Mash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlScheme_Mash.Unmarshal(m, b)
}
func (m *ControlScheme_Mash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlScheme_Mash.Marshal(b, m, deterministic)
}
func (m *ControlScheme_Mash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlScheme_Mash.Merge(m, src)
}
func (m *ControlScheme_Mash) XXX_Size() int {
	return xxx_messageInfo_ControlScheme_Mash.Size(m)
}
func (m *ControlScheme_Mash) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlScheme_Mash.DiscardUnknown(m)
}

var xxx_messageInfo_ControlScheme_Mash proto.InternalMessageInfo

func (m *ControlScheme_Mash) GetConstraints() []*Constraint {
	if m != nil {
		return m.Constraints
	}
	return nil
}

type ControlScheme_Power struct {
	PowerLevel           float64  `protobuf:"fixed64,1,opt,name=power_level,json=powerLevel,proto3" json:"power_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlScheme_Power) Reset()         { *m = ControlScheme_Power{} }
func (m *ControlScheme_Power) String() string { return proto.CompactTextString(m) }
func (*ControlScheme_Power) ProtoMessage()    {}
func (*ControlScheme_Power) Descriptor() ([]byte, []int) {
	return fileDescriptor_04154031a803dc7e, []int{1, 2}
}

func (m *ControlScheme_Power) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlScheme_Power.Unmarshal(m, b)
}
func (m *ControlScheme_Power) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlScheme_Power.Marshal(b, m, deterministic)
}
func (m *ControlScheme_Power) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlScheme_Power.Merge(m, src)
}
func (m *ControlScheme_Power) XXX_Size() int {
	return xxx_messageInfo_ControlScheme_Power.Size(m)
}
func (m *ControlScheme_Power) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlScheme_Power.DiscardUnknown(m)
}

var xxx_messageInfo_ControlScheme_Power proto.InternalMessageInfo

func (m *ControlScheme_Power) GetPowerLevel() float64 {
	if m != nil {
		return m.PowerLevel
	}
	return 0
}

type ControlRequest struct {
	Scheme               *ControlScheme `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ControlRequest) Reset()         { *m = ControlRequest{} }
func (m *ControlRequest) String() string { return proto.CompactTextString(m) }
func (*ControlRequest) ProtoMessage()    {}
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04154031a803dc7e, []int{2}
}

func (m *ControlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlRequest.Unmarshal(m, b)
}
func (m *ControlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlRequest.Marshal(b, m, deterministic)
}
func (m *ControlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlRequest.Merge(m, src)
}
func (m *ControlRequest) XXX_Size() int {
	return xxx_messageInfo_ControlRequest.Size(m)
}
func (m *ControlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControlRequest proto.InternalMessageInfo

func (m *ControlRequest) GetScheme() *ControlScheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

type ControlResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlResponse) Reset()         { *m = ControlResponse{} }
func (m *ControlResponse) String() string { return proto.CompactTextString(m) }
func (*ControlResponse) ProtoMessage()    {}
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04154031a803dc7e, []int{3}
}

func (m *ControlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlResponse.Unmarshal(m, b)
}
func (m *ControlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlResponse.Marshal(b, m, deterministic)
}
func (m *ControlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlResponse.Merge(m, src)
}
func (m *ControlResponse) XXX_Size() int {
	return xxx_messageInfo_ControlResponse.Size(m)
}
func (m *ControlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControlResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Constraint)(nil), "brewery.model.Constraint")
	proto.RegisterType((*ControlScheme)(nil), "brewery.model.ControlScheme")
	proto.RegisterType((*ControlScheme_Boil)(nil), "brewery.model.ControlScheme.Boil")
	proto.RegisterType((*ControlScheme_Mash)(nil), "brewery.model.ControlScheme.Mash")
	proto.RegisterType((*ControlScheme_Power)(nil), "brewery.model.ControlScheme.Power")
	proto.RegisterType((*ControlRequest)(nil), "brewery.model.ControlRequest")
	proto.RegisterType((*ControlResponse)(nil), "brewery.model.ControlResponse")
}

func init() { proto.RegisterFile("brewery.proto", fileDescriptor_04154031a803dc7e) }

var fileDescriptor_04154031a803dc7e = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4f, 0xbb, 0x40,
	0x10, 0xc6, 0xbb, 0x7d, 0xfd, 0xff, 0x87, 0xd4, 0x97, 0x3d, 0x21, 0xf1, 0x05, 0x39, 0x71, 0xe2,
	0x80, 0x26, 0x26, 0x7a, 0x83, 0xc4, 0x34, 0x46, 0x13, 0xb3, 0xc6, 0xb3, 0x81, 0x3a, 0x09, 0x44,
	0x60, 0x71, 0x17, 0x6d, 0xfb, 0xe5, 0xfc, 0x6c, 0x66, 0x97, 0x2d, 0xb1, 0x51, 0xeb, 0x6d, 0x78,
	0x66, 0x9e, 0xdf, 0x3c, 0x4c, 0x16, 0xa6, 0xa9, 0xc0, 0x05, 0x8a, 0x55, 0x50, 0x0b, 0xde, 0x70,
	0xda, 0x7d, 0x96, 0xfc, 0x19, 0x0b, 0x2f, 0x02, 0x88, 0x79, 0x25, 0x1b, 0x91, 0xe4, 0x55, 0x43,
	0xf7, 0x60, 0xf0, 0x82, 0x2b, 0x9b, 0xb8, 0xc4, 0xff, 0xcf, 0x54, 0xa9, 0x94, 0x32, 0xaf, 0xec,
	0xbe, 0x4b, 0x7c, 0xc2, 0x54, 0xa9, 0x95, 0x64, 0x69, 0x0f, 0x8c, 0x92, 0x2c, 0xbd, 0x8f, 0x3e,
	0x4c, 0x63, 0x5e, 0x35, 0x82, 0x17, 0x0f, 0xf3, 0x0c, 0x4b, 0xa4, 0x17, 0x30, 0x4c, 0x79, 0x5e,
	0x68, 0x90, 0x15, 0x9e, 0x06, 0x1b, 0x3b, 0x83, 0x8d, 0xd9, 0x20, 0xe2, 0x79, 0x31, 0xeb, 0x31,
	0x6d, 0x50, 0xc6, 0x32, 0x91, 0x99, 0xde, 0xf7, 0x97, 0xf1, 0x2e, 0x91, 0x99, 0x32, 0x2a, 0x03,
	0xbd, 0x84, 0x51, 0xcd, 0x17, 0x28, 0x74, 0x2e, 0x2b, 0xf4, 0xb6, 0x3a, 0xef, 0xd5, 0xe4, 0xac,
	0xc7, 0x5a, 0x8b, 0x33, 0x86, 0xa1, 0x0a, 0xe1, 0xc4, 0x30, 0x54, 0x4c, 0x7a, 0x05, 0xd6, 0xbc,
	0xbb, 0x89, 0xb4, 0x89, 0x3b, 0xf0, 0xad, 0xf0, 0xe0, 0x3b, 0xd1, 0x4c, 0xb0, 0xaf, 0xd3, 0x8e,
	0x0f, 0x23, 0x8d, 0xa7, 0x27, 0x60, 0x69, 0xfc, 0x53, 0x81, 0xef, 0xd8, 0x9e, 0x82, 0x30, 0xd0,
	0xd2, 0xad, 0x52, 0xa2, 0x7f, 0x30, 0x96, 0x3a, 0x8f, 0x77, 0x0d, 0x3b, 0x26, 0x20, 0xc3, 0xd7,
	0x37, 0x94, 0x0d, 0x3d, 0x5f, 0xf7, 0xcc, 0x09, 0x0f, 0xb7, 0xfd, 0x0f, 0x5b, 0x73, 0xf6, 0x61,
	0xb7, 0xe3, 0xc8, 0x9a, 0x57, 0x12, 0xc3, 0x47, 0x98, 0x44, 0xad, 0x93, 0xde, 0xc0, 0xc4, 0x74,
	0xe9, 0xd1, 0xcf, 0x38, 0xb3, 0xdd, 0x39, 0xfe, 0xad, 0xdd, 0x42, 0xbd, 0x5e, 0x3a, 0xd6, 0x8f,
	0xe9, 0xec, 0x33, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x94, 0xfe, 0xa8, 0x5d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BreweryClient is the client API for Brewery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BreweryClient interface {
	Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error)
}

type breweryClient struct {
	cc *grpc.ClientConn
}

func NewBreweryClient(cc *grpc.ClientConn) BreweryClient {
	return &breweryClient{cc}
}

func (c *breweryClient) Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, "/brewery.model.Brewery/Control", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreweryServer is the server API for Brewery service.
type BreweryServer interface {
	Control(context.Context, *ControlRequest) (*ControlResponse, error)
}

// UnimplementedBreweryServer can be embedded to have forward compatible implementations.
type UnimplementedBreweryServer struct {
}

func (*UnimplementedBreweryServer) Control(ctx context.Context, req *ControlRequest) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Control not implemented")
}

func RegisterBreweryServer(s *grpc.Server, srv BreweryServer) {
	s.RegisterService(&_Brewery_serviceDesc, srv)
}

func _Brewery_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreweryServer).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewery.model.Brewery/Control",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreweryServer).Control(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Brewery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "brewery.model.Brewery",
	HandlerType: (*BreweryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Control",
			Handler:    _Brewery_Control_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brewery.proto",
}
