// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package brewery_model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type TemperatureSensor struct {
	Serial               string    `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TemperatureSensor) Reset()         { *m = TemperatureSensor{} }
func (m *TemperatureSensor) String() string { return proto.CompactTextString(m) }
func (*TemperatureSensor) ProtoMessage()    {}
func (*TemperatureSensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *TemperatureSensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemperatureSensor.Unmarshal(m, b)
}
func (m *TemperatureSensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemperatureSensor.Marshal(b, m, deterministic)
}
func (m *TemperatureSensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemperatureSensor.Merge(m, src)
}
func (m *TemperatureSensor) XXX_Size() int {
	return xxx_messageInfo_TemperatureSensor.Size(m)
}
func (m *TemperatureSensor) XXX_DiscardUnknown() {
	xxx_messageInfo_TemperatureSensor.DiscardUnknown(m)
}

var xxx_messageInfo_TemperatureSensor proto.InternalMessageInfo

func (m *TemperatureSensor) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *TemperatureSensor) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *TemperatureSensor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SSR struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SSR) Reset()         { *m = SSR{} }
func (m *SSR) String() string { return proto.CompactTextString(m) }
func (*SSR) ProtoMessage()    {}
func (*SSR) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *SSR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSR.Unmarshal(m, b)
}
func (m *SSR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSR.Marshal(b, m, deterministic)
}
func (m *SSR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSR.Merge(m, src)
}
func (m *SSR) XXX_Size() int {
	return xxx_messageInfo_SSR.Size(m)
}
func (m *SSR) XXX_DiscardUnknown() {
	xxx_messageInfo_SSR.DiscardUnknown(m)
}

var xxx_messageInfo_SSR proto.InternalMessageInfo

func (m *SSR) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *SSR) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BreweryConfig struct {
	Mash                 *TemperatureSensor `protobuf:"bytes,1,opt,name=mash,proto3" json:"mash,omitempty"`
	Boil                 *TemperatureSensor `protobuf:"bytes,2,opt,name=boil,proto3" json:"boil,omitempty"`
	Herms                *TemperatureSensor `protobuf:"bytes,3,opt,name=herms,proto3" json:"herms,omitempty"`
	BoilHeater           *SSR               `protobuf:"bytes,4,opt,name=boil_heater,json=boilHeater,proto3" json:"boil_heater,omitempty"`
	Scheme               *ControlScheme     `protobuf:"bytes,5,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BreweryConfig) Reset()         { *m = BreweryConfig{} }
func (m *BreweryConfig) String() string { return proto.CompactTextString(m) }
func (*BreweryConfig) ProtoMessage()    {}
func (*BreweryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *BreweryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreweryConfig.Unmarshal(m, b)
}
func (m *BreweryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreweryConfig.Marshal(b, m, deterministic)
}
func (m *BreweryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreweryConfig.Merge(m, src)
}
func (m *BreweryConfig) XXX_Size() int {
	return xxx_messageInfo_BreweryConfig.Size(m)
}
func (m *BreweryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BreweryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BreweryConfig proto.InternalMessageInfo

func (m *BreweryConfig) GetMash() *TemperatureSensor {
	if m != nil {
		return m.Mash
	}
	return nil
}

func (m *BreweryConfig) GetBoil() *TemperatureSensor {
	if m != nil {
		return m.Boil
	}
	return nil
}

func (m *BreweryConfig) GetHerms() *TemperatureSensor {
	if m != nil {
		return m.Herms
	}
	return nil
}

func (m *BreweryConfig) GetBoilHeater() *SSR {
	if m != nil {
		return m.BoilHeater
	}
	return nil
}

func (m *BreweryConfig) GetScheme() *ControlScheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "brewery.model.Location")
	proto.RegisterType((*TemperatureSensor)(nil), "brewery.model.TemperatureSensor")
	proto.RegisterType((*SSR)(nil), "brewery.model.SSR")
	proto.RegisterType((*BreweryConfig)(nil), "brewery.model.BreweryConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x4a, 0xc4, 0x40,
	0x10, 0xc6, 0xc9, 0xfd, 0xe3, 0x9c, 0xf3, 0x0a, 0xb7, 0xd0, 0x20, 0x22, 0x21, 0xd5, 0x55, 0x29,
	0xcc, 0xe1, 0x03, 0x78, 0x8d, 0x85, 0x58, 0xec, 0xda, 0xcb, 0x26, 0x8e, 0x26, 0x90, 0xcd, 0x84,
	0xc9, 0x8a, 0xf8, 0x32, 0x3e, 0xab, 0xec, 0x66, 0x3d, 0xbc, 0xd8, 0x9c, 0xdd, 0x0c, 0xf9, 0xfd,
	0xbe, 0x8f, 0x09, 0x0b, 0xa7, 0x25, 0xb5, 0xaf, 0xf5, 0x5b, 0xd6, 0x31, 0x59, 0x12, 0xeb, 0x82,
	0xf1, 0x03, 0xf9, 0x33, 0x33, 0xf4, 0x82, 0xcd, 0xe5, 0x7e, 0xf5, 0x5f, 0xd3, 0x6b, 0x58, 0x3e,
	0x50, 0xa9, 0x6d, 0x4d, 0xad, 0x10, 0x30, 0xeb, 0x88, 0x6d, 0x1c, 0x25, 0xd1, 0xe6, 0x44, 0xfa,
	0x39, 0xb5, 0x70, 0xf6, 0x84, 0xa6, 0x43, 0xd6, 0xf6, 0x9d, 0x51, 0x61, 0xdb, 0x13, 0x8b, 0x73,
	0x58, 0xf4, 0xc8, 0xb5, 0x6e, 0x02, 0x1a, 0x36, 0x91, 0xc3, 0xb2, 0x09, 0x61, 0xf1, 0x24, 0x89,
	0x36, 0xab, 0x9b, 0x8b, 0xec, 0xa0, 0x3d, 0xfb, 0xe9, 0x92, 0x7b, 0xd0, 0xb5, 0xb6, 0xda, 0x60,
	0x3c, 0x1d, 0x5a, 0xdd, 0x9c, 0x3e, 0xc2, 0x54, 0x29, 0x79, 0x90, 0x17, 0xfd, 0x37, 0x6f, 0xf2,
	0x2b, 0xef, 0x6b, 0x02, 0xeb, 0xbb, 0x41, 0xdc, 0xf9, 0x7f, 0x23, 0xb6, 0x30, 0x33, 0xba, 0xaf,
	0x42, 0x6c, 0x32, 0x8a, 0xfd, 0x73, 0xb2, 0xf4, 0xb4, 0xb3, 0x0a, 0xaa, 0x9b, 0x70, 0xdc, 0x11,
	0x96, 0xa3, 0xc5, 0x2d, 0xcc, 0x2b, 0x64, 0xd3, 0xfb, 0x13, 0x8f, 0xd1, 0x06, 0x5c, 0xe4, 0xb0,
	0x72, 0xfe, 0x73, 0x85, 0xda, 0x22, 0xc7, 0x33, 0x6f, 0x8b, 0x91, 0xad, 0x94, 0x94, 0xe0, 0xb0,
	0x7b, 0x4f, 0x89, 0x2d, 0x2c, 0xfa, 0xb2, 0x42, 0x83, 0xf1, 0xdc, 0xf3, 0x57, 0x23, 0x7e, 0x47,
	0xad, 0x65, 0x6a, 0x94, 0x67, 0x64, 0x60, 0x8b, 0x85, 0x7f, 0x0d, 0xf9, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb9, 0x09, 0xaf, 0xb7, 0x3b, 0x02, 0x00, 0x00,
}
