// Code generated by protoc-gen-go. DO NOT EDIT.
// source: switch.proto

package brewery_model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OnRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnRequest) Reset()         { *m = OnRequest{} }
func (m *OnRequest) String() string { return proto.CompactTextString(m) }
func (*OnRequest) ProtoMessage()    {}
func (*OnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_b3102f5f37bd44d0, []int{0}
}
func (m *OnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRequest.Unmarshal(m, b)
}
func (m *OnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRequest.Marshal(b, m, deterministic)
}
func (dst *OnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRequest.Merge(dst, src)
}
func (m *OnRequest) XXX_Size() int {
	return xxx_messageInfo_OnRequest.Size(m)
}
func (m *OnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnRequest proto.InternalMessageInfo

type OnResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnResponse) Reset()         { *m = OnResponse{} }
func (m *OnResponse) String() string { return proto.CompactTextString(m) }
func (*OnResponse) ProtoMessage()    {}
func (*OnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_b3102f5f37bd44d0, []int{1}
}
func (m *OnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnResponse.Unmarshal(m, b)
}
func (m *OnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnResponse.Marshal(b, m, deterministic)
}
func (dst *OnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnResponse.Merge(dst, src)
}
func (m *OnResponse) XXX_Size() int {
	return xxx_messageInfo_OnResponse.Size(m)
}
func (m *OnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnResponse proto.InternalMessageInfo

type OffRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffRequest) Reset()         { *m = OffRequest{} }
func (m *OffRequest) String() string { return proto.CompactTextString(m) }
func (*OffRequest) ProtoMessage()    {}
func (*OffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_b3102f5f37bd44d0, []int{2}
}
func (m *OffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffRequest.Unmarshal(m, b)
}
func (m *OffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffRequest.Marshal(b, m, deterministic)
}
func (dst *OffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffRequest.Merge(dst, src)
}
func (m *OffRequest) XXX_Size() int {
	return xxx_messageInfo_OffRequest.Size(m)
}
func (m *OffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OffRequest proto.InternalMessageInfo

type OffResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffResponse) Reset()         { *m = OffResponse{} }
func (m *OffResponse) String() string { return proto.CompactTextString(m) }
func (*OffResponse) ProtoMessage()    {}
func (*OffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_b3102f5f37bd44d0, []int{3}
}
func (m *OffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffResponse.Unmarshal(m, b)
}
func (m *OffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffResponse.Marshal(b, m, deterministic)
}
func (dst *OffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffResponse.Merge(dst, src)
}
func (m *OffResponse) XXX_Size() int {
	return xxx_messageInfo_OffResponse.Size(m)
}
func (m *OffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OffResponse proto.InternalMessageInfo

type ToggleOnRequest struct {
	IntervalMs           int64    `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleOnRequest) Reset()         { *m = ToggleOnRequest{} }
func (m *ToggleOnRequest) String() string { return proto.CompactTextString(m) }
func (*ToggleOnRequest) ProtoMessage()    {}
func (*ToggleOnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_b3102f5f37bd44d0, []int{4}
}
func (m *ToggleOnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleOnRequest.Unmarshal(m, b)
}
func (m *ToggleOnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleOnRequest.Marshal(b, m, deterministic)
}
func (dst *ToggleOnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleOnRequest.Merge(dst, src)
}
func (m *ToggleOnRequest) XXX_Size() int {
	return xxx_messageInfo_ToggleOnRequest.Size(m)
}
func (m *ToggleOnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleOnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleOnRequest proto.InternalMessageInfo

func (m *ToggleOnRequest) GetIntervalMs() int64 {
	if m != nil {
		return m.IntervalMs
	}
	return 0
}

type ToggleOnResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleOnResponse) Reset()         { *m = ToggleOnResponse{} }
func (m *ToggleOnResponse) String() string { return proto.CompactTextString(m) }
func (*ToggleOnResponse) ProtoMessage()    {}
func (*ToggleOnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_b3102f5f37bd44d0, []int{5}
}
func (m *ToggleOnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleOnResponse.Unmarshal(m, b)
}
func (m *ToggleOnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleOnResponse.Marshal(b, m, deterministic)
}
func (dst *ToggleOnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleOnResponse.Merge(dst, src)
}
func (m *ToggleOnResponse) XXX_Size() int {
	return xxx_messageInfo_ToggleOnResponse.Size(m)
}
func (m *ToggleOnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleOnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleOnResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*OnRequest)(nil), "brewery.model.OnRequest")
	proto.RegisterType((*OnResponse)(nil), "brewery.model.OnResponse")
	proto.RegisterType((*OffRequest)(nil), "brewery.model.OffRequest")
	proto.RegisterType((*OffResponse)(nil), "brewery.model.OffResponse")
	proto.RegisterType((*ToggleOnRequest)(nil), "brewery.model.ToggleOnRequest")
	proto.RegisterType((*ToggleOnResponse)(nil), "brewery.model.ToggleOnResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SwitchClient is the client API for Switch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SwitchClient interface {
	On(ctx context.Context, in *OnRequest, opts ...grpc.CallOption) (*OnResponse, error)
	Off(ctx context.Context, in *OffRequest, opts ...grpc.CallOption) (*OffResponse, error)
	ToggleOn(ctx context.Context, in *ToggleOnRequest, opts ...grpc.CallOption) (*ToggleOnResponse, error)
}

type switchClient struct {
	cc *grpc.ClientConn
}

func NewSwitchClient(cc *grpc.ClientConn) SwitchClient {
	return &switchClient{cc}
}

func (c *switchClient) On(ctx context.Context, in *OnRequest, opts ...grpc.CallOption) (*OnResponse, error) {
	out := new(OnResponse)
	err := c.cc.Invoke(ctx, "/brewery.model.Switch/On", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchClient) Off(ctx context.Context, in *OffRequest, opts ...grpc.CallOption) (*OffResponse, error) {
	out := new(OffResponse)
	err := c.cc.Invoke(ctx, "/brewery.model.Switch/Off", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchClient) ToggleOn(ctx context.Context, in *ToggleOnRequest, opts ...grpc.CallOption) (*ToggleOnResponse, error) {
	out := new(ToggleOnResponse)
	err := c.cc.Invoke(ctx, "/brewery.model.Switch/ToggleOn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwitchServer is the server API for Switch service.
type SwitchServer interface {
	On(context.Context, *OnRequest) (*OnResponse, error)
	Off(context.Context, *OffRequest) (*OffResponse, error)
	ToggleOn(context.Context, *ToggleOnRequest) (*ToggleOnResponse, error)
}

func RegisterSwitchServer(s *grpc.Server, srv SwitchServer) {
	s.RegisterService(&_Switch_serviceDesc, srv)
}

func _Switch_On_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchServer).On(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewery.model.Switch/On",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchServer).On(ctx, req.(*OnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Switch_Off_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchServer).Off(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewery.model.Switch/Off",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchServer).Off(ctx, req.(*OffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Switch_ToggleOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchServer).ToggleOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewery.model.Switch/ToggleOn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchServer).ToggleOn(ctx, req.(*ToggleOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Switch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "brewery.model.Switch",
	HandlerType: (*SwitchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "On",
			Handler:    _Switch_On_Handler,
		},
		{
			MethodName: "Off",
			Handler:    _Switch_Off_Handler,
		},
		{
			MethodName: "ToggleOn",
			Handler:    _Switch_ToggleOn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "switch.proto",
}

func init() { proto.RegisterFile("switch.proto", fileDescriptor_switch_b3102f5f37bd44d0) }

var fileDescriptor_switch_b3102f5f37bd44d0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0xcf, 0x2c,
	0x49, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4d, 0x2a, 0x4a, 0x2d, 0x4f, 0x2d,
	0xaa, 0xd4, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0xe2, 0xe6, 0xe2, 0xf4, 0xcf, 0x0b, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0xe2, 0xe1, 0xe2, 0x02, 0x71, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0xc1, 0xbc, 0xb4, 0x34, 0x98, 0x1c, 0x2f, 0x17, 0x37, 0x98, 0x07, 0x95, 0x34, 0xe2, 0xe2, 0x0f,
	0xc9, 0x4f, 0x4f, 0xcf, 0x49, 0x85, 0xeb, 0x16, 0x92, 0xe7, 0xe2, 0xce, 0xcc, 0x2b, 0x49, 0x2d,
	0x2a, 0x4b, 0xcc, 0x89, 0xcf, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0xe2, 0x82, 0x09,
	0xf9, 0x16, 0x2b, 0x09, 0x71, 0x09, 0x20, 0xf4, 0x40, 0xcc, 0x31, 0xba, 0xc2, 0xc8, 0xc5, 0x16,
	0x0c, 0x76, 0x9f, 0x90, 0x35, 0x17, 0x93, 0x7f, 0x9e, 0x90, 0x84, 0x1e, 0x8a, 0x03, 0xf5, 0xe0,
	0xe6, 0x4b, 0x49, 0x62, 0x91, 0x81, 0xba, 0x86, 0x41, 0xc8, 0x8e, 0x8b, 0xd9, 0x3f, 0x2d, 0x4d,
	0x08, 0x43, 0x0d, 0xdc, 0x03, 0x52, 0x52, 0xd8, 0xa4, 0xe0, 0xfa, 0x7d, 0xb9, 0x38, 0x60, 0x6e,
	0x13, 0x92, 0x43, 0x53, 0x89, 0xe6, 0x51, 0x29, 0x79, 0x9c, 0xf2, 0x30, 0xe3, 0x92, 0xd8, 0xc0,
	0x81, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xfa, 0x84, 0x96, 0x7c, 0x01, 0x00, 0x00,
}
