language: go

go:
  - 1.11.5

env:
  - GO111MODULE=on

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go install github.com/mattn/goveralls

# before_script:
#   - go install github.com/golangci/golangci-lint/cmd/golangci-lint
#   - go install github.com/kyoh86/richgo
#   - go install github.com/mattn/goveralls

install:
  - dep ensure
#   - dep ensure -v
#   - go get -u github.com/golang/dep/cmd/dep
#   - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
#   - go get github.com/mattn/goveralls

script:
  - make tests
  - ${GOPATH}/bin/goveralls -coverprofile=coverage.out -service=travis-ci