language: go

go:
  - 1.10.x

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/kyoh86/richgo
  - go get github.com/mattn/goveralls
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - dep ensure -v

script:
  - ${GOPATH}/bin/golangci-lint run ./...
  - go test -coverprofile coverage.out ./...
  - ${GOPATH}/bin/goveralls -coverprofile coverage.out -service=travis-ci