language: go

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  - GO111MODULE=on

script:
  - make tests
  - ${GOPATH}/bin/goveralls -coverprofile=coverage.out -service=travis-ci