# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

script:
  - go test -v -race -mod=vendor ./...