language: go

go:
  - 1.12.x

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script:
  - make test-ci
  - make install-golang-ci
  - ${GOPATH}/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - golangci-lint run