language: go

go:
  - 1.10.x

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/kyoh86/richgo
  - go get github.com/mattn/goveralls
  - dep ensure -v

script:
  - make test-ci
  - ${GOPATH}/bin/goveralls -coverprofile=coverage.out -service=travis-ci