sudo: false
language: go

go:
  - tip

env:
  - GO111MODULE=on

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script:
  - make test-ci
  - make lint-ci
  - ${GOPATH}/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - make lint