apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: brewery-deployment
  labels:
    app: brewery
spec:
  selector:
    matchLabels:
      app: brewery
  replicas: 1
  template:
    metadata:
      labels:
        app: brewery
    spec:
      containers:
      - name: brewery
        image: local/brewery
        imagePullPolicy: Never
        ports:
        - name: brewery-service
          containerPort: 9000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MASH_THERM_ADDRESS_0
            value: "localhost:9110"
          - name: HERMS_THERM_ADDRESS_0
            value: "localhost:9111"
          - name: BOIL_THERM_ADDRESS_0
            value: "localhost:9112"
          - name: ELEMENT_ADDRESS_0
            value: "localhost:9100"
          - name: BREWERY_PORT_0
            value: "9000"
      - name: element
        image: local/element
        imagePullPolicy: Never
        ports:
        - name: element-service
          containerPort: 9100
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
      - name: therm-mash
        image: local/thermometer
        imagePullPolicy: Never
        ports:
        - name: therm-mash-srv
          containerPort: 9110
        env:
          - name: THERM_PORT
            value: "9110"
          - name: THERM_ADDR
            value: "28-0315712c08ff"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
      - name: therm-herms
        image: local/thermometer
        imagePullPolicy: Never
        ports:
        - name: therm-herms-srv
          containerPort: 9111
        env:
          - name: THERM_PORT
            value: "9111"
          - name: THERM_ADDR
            value: "28-0315715039ff"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "125Mi"
            cpu: "250m"
      - name: therm-boil
        image: local/thermometer
        imagePullPolicy: Never
        ports:
        - name: therm-boil-srv
          containerPort: 9112
        env:
          - name: THERM_PORT
            value: "9112"
          - name: THERM_ADDR
            value: "28-031571188aff"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: brewery-service
spec:
  selector:
    app: brewery
  ports:
  - port: 9000
    targetPort: brewery-service