
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
required = [
    "github.com/golang/protobuf/protoc-gen-go",
    "github.com/kyoh86/richgo",
]

source = "https://github.com/mkuchenbecker/brewery3.git"

[[constraint]]
  name = "github.com/mkuchenbecker/brewery3"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
