
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
required = [
    "github.com/golang/protobuf/protoc-gen-go",
    "github.com/kyoh86/richgo",
    "github.com/t-yuki/gocover-cobertura",
    "k8s.io/api",
    "k8s.io/apimachinery",
    "k8s.io/client-go"
]

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"