// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/protos/data.proto

package data

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Double
	//	*Value_Float
	//	*Value_Int32
	//	*Value_Int64
	//	*Value_String_
	//	*Value_Bool
	//	*Value_Uint32
	//	*Value_Uint64
	//	*Value_Bytes
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6a1143f5914b74, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_Double struct {
	Double float64 `protobuf:"fixed64,2,opt,name=double,proto3,oneof"`
}

type Value_Float struct {
	Float float32 `protobuf:"fixed32,3,opt,name=float,proto3,oneof"`
}

type Value_Int32 struct {
	Int32 int32 `protobuf:"varint,4,opt,name=int32,proto3,oneof"`
}

type Value_Int64 struct {
	Int64 int64 `protobuf:"varint,5,opt,name=int64,proto3,oneof"`
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,6,opt,name=string,proto3,oneof"`
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,7,opt,name=bool,proto3,oneof"`
}

type Value_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,8,opt,name=uint32,proto3,oneof"`
}

type Value_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,9,opt,name=uint64,proto3,oneof"`
}

type Value_Bytes struct {
	Bytes []byte `protobuf:"bytes,10,opt,name=bytes,proto3,oneof"`
}

func (*Value_Double) isValue_Value() {}

func (*Value_Float) isValue_Value() {}

func (*Value_Int32) isValue_Value() {}

func (*Value_Int64) isValue_Value() {}

func (*Value_String_) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (*Value_Uint32) isValue_Value() {}

func (*Value_Uint64) isValue_Value() {}

func (*Value_Bytes) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetDouble() float64 {
	if x, ok := m.GetValue().(*Value_Double); ok {
		return x.Double
	}
	return 0
}

func (m *Value) GetFloat() float32 {
	if x, ok := m.GetValue().(*Value_Float); ok {
		return x.Float
	}
	return 0
}

func (m *Value) GetInt32() int32 {
	if x, ok := m.GetValue().(*Value_Int32); ok {
		return x.Int32
	}
	return 0
}

func (m *Value) GetInt64() int64 {
	if x, ok := m.GetValue().(*Value_Int64); ok {
		return x.Int64
	}
	return 0
}

func (m *Value) GetString_() string {
	if x, ok := m.GetValue().(*Value_String_); ok {
		return x.String_
	}
	return ""
}

func (m *Value) GetBool() bool {
	if x, ok := m.GetValue().(*Value_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *Value) GetUint32() uint32 {
	if x, ok := m.GetValue().(*Value_Uint32); ok {
		return x.Uint32
	}
	return 0
}

func (m *Value) GetUint64() uint64 {
	if x, ok := m.GetValue().(*Value_Uint64); ok {
		return x.Uint64
	}
	return 0
}

func (m *Value) GetBytes() []byte {
	if x, ok := m.GetValue().(*Value_Bytes); ok {
		return x.Bytes
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Double)(nil),
		(*Value_Float)(nil),
		(*Value_Int32)(nil),
		(*Value_Int64)(nil),
		(*Value_String_)(nil),
		(*Value_Bool)(nil),
		(*Value_Uint32)(nil),
		(*Value_Uint64)(nil),
		(*Value_Bytes)(nil),
	}
}

type DataObject struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields               map[string]*Value `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataObject) Reset()         { *m = DataObject{} }
func (m *DataObject) String() string { return proto.CompactTextString(m) }
func (*DataObject) ProtoMessage()    {}
func (*DataObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6a1143f5914b74, []int{1}
}

func (m *DataObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataObject.Unmarshal(m, b)
}
func (m *DataObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataObject.Marshal(b, m, deterministic)
}
func (m *DataObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataObject.Merge(m, src)
}
func (m *DataObject) XXX_Size() int {
	return xxx_messageInfo_DataObject.Size(m)
}
func (m *DataObject) XXX_DiscardUnknown() {
	xxx_messageInfo_DataObject.DiscardUnknown(m)
}

var xxx_messageInfo_DataObject proto.InternalMessageInfo

func (m *DataObject) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataObject) GetFields() map[string]*Value {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetResponse struct {
	Data                 []*DataObject `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6a1143f5914b74, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetData() []*DataObject {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6a1143f5914b74, []int{3}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6a1143f5914b74, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*Value)(nil), "data.Value")
	proto.RegisterType((*DataObject)(nil), "data.DataObject")
	proto.RegisterMapType((map[string]*Value)(nil), "data.DataObject.FieldsEntry")
	proto.RegisterType((*GetResponse)(nil), "data.GetResponse")
	proto.RegisterType((*SendResponse)(nil), "data.SendResponse")
	proto.RegisterType((*GetRequest)(nil), "data.GetRequest")
}

func init() { proto.RegisterFile("data/protos/data.proto", fileDescriptor_8f6a1143f5914b74) }

var fileDescriptor_8f6a1143f5914b74 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x8d, 0xf3, 0xb5, 0xbb, 0x93, 0x5d, 0x54, 0x2c, 0x54, 0x59, 0x15, 0x42, 0x26, 0xe2, 0xe0,
	0x03, 0x4a, 0xa5, 0x34, 0x8a, 0x10, 0x47, 0x04, 0x6d, 0x6f, 0x20, 0x23, 0x71, 0x4f, 0x1a, 0x17,
	0x15, 0x42, 0x5c, 0x62, 0x07, 0xa9, 0xff, 0x85, 0xdf, 0xc8, 0x6f, 0x40, 0xb6, 0x13, 0xb5, 0xb0,
	0xbd, 0xcd, 0x7b, 0xf3, 0xfc, 0xde, 0x78, 0x6c, 0x98, 0x37, 0x95, 0xae, 0x96, 0xc7, 0x5e, 0x6a,
	0xa9, 0x96, 0xa6, 0xce, 0x6c, 0x8d, 0x43, 0x53, 0xa7, 0x7f, 0x10, 0x44, 0x5f, 0xaa, 0x76, 0x10,
	0x98, 0x40, 0xdc, 0xc8, 0xa1, 0x6e, 0x05, 0xf1, 0x29, 0x62, 0x68, 0xeb, 0xf1, 0x11, 0xe3, 0x39,
	0x44, 0xfb, 0x56, 0x56, 0x9a, 0x04, 0x14, 0x31, 0x7f, 0xeb, 0x71, 0x07, 0x0d, 0x7f, 0xe8, 0xf4,
	0x2a, 0x27, 0x21, 0x45, 0x2c, 0x32, 0xbc, 0x85, 0x23, 0x5f, 0x16, 0x24, 0xa2, 0x88, 0x05, 0x23,
	0x5f, 0x16, 0x26, 0x41, 0xe9, 0xfe, 0xd0, 0x7d, 0x25, 0x31, 0x45, 0xec, 0xce, 0x24, 0x38, 0x8c,
	0x9f, 0x41, 0x58, 0x4b, 0xd9, 0x92, 0x1b, 0x8a, 0xd8, 0xed, 0xd6, 0xe3, 0x16, 0x19, 0xfd, 0xe0,
	0x02, 0x6e, 0x29, 0x62, 0x0f, 0x46, 0xef, 0xf0, 0xd4, 0x29, 0x0b, 0x72, 0x47, 0x11, 0x0b, 0xa7,
	0x4e, 0x59, 0x98, 0xec, 0xfa, 0xa4, 0x85, 0x22, 0x40, 0x11, 0xbb, 0x37, 0xd9, 0x16, 0xbe, 0xbb,
	0x81, 0xe8, 0x97, 0xb9, 0x66, 0xfa, 0x1b, 0x01, 0xbc, 0xaf, 0x74, 0xf5, 0xb1, 0xfe, 0x26, 0x76,
	0x1a, 0xcf, 0x20, 0xf8, 0x2e, 0x4e, 0x04, 0x99, 0x81, 0xb8, 0x29, 0x71, 0x01, 0xf1, 0xfe, 0x20,
	0xda, 0x46, 0x11, 0x9f, 0x06, 0x2c, 0xc9, 0x9f, 0x67, 0x76, 0x69, 0xe7, 0x33, 0xd9, 0xda, 0xb6,
	0x3f, 0x74, 0xba, 0x3f, 0xf1, 0x51, 0xbb, 0x58, 0x43, 0x72, 0x41, 0x5f, 0xb1, 0x7d, 0x39, 0x0e,
	0x60, 0xb7, 0x9b, 0xe4, 0x89, 0x73, 0xb5, 0xab, 0xe7, 0xae, 0xf3, 0xd6, 0x7f, 0x83, 0xd2, 0x15,
	0x24, 0x1b, 0xa1, 0xb9, 0x50, 0x47, 0xd9, 0x29, 0x81, 0x5f, 0x81, 0x7d, 0x26, 0x82, 0xec, 0x28,
	0xb3, 0xff, 0x47, 0xe1, 0xee, 0x11, 0x9f, 0xc0, 0xfd, 0x67, 0xd1, 0x35, 0xd3, 0xa9, 0xf4, 0x05,
	0x80, 0x35, 0xf9, 0x39, 0x08, 0x75, 0xe5, 0x8a, 0xf9, 0x0f, 0x78, 0x30, 0x1e, 0x9f, 0x7a, 0xb9,
	0x13, 0x4a, 0xc9, 0x1e, 0x67, 0x10, 0x1a, 0x03, 0xfc, 0x28, 0x60, 0x81, 0x1d, 0xf3, 0x8f, 0xbd,
	0x87, 0x5f, 0x43, 0xb0, 0x11, 0x7a, 0x92, 0x9f, 0xb3, 0x16, 0x4f, 0x2f, 0x98, 0x49, 0x5d, 0xc7,
	0xf6, 0xc3, 0xad, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x37, 0x63, 0x8c, 0x17, 0x8a, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataProcessorClient is the client API for DataProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataProcessorClient interface {
	Send(ctx context.Context, in *DataObject, opts ...grpc.CallOption) (*SendResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type dataProcessorClient struct {
	cc *grpc.ClientConn
}

func NewDataProcessorClient(cc *grpc.ClientConn) DataProcessorClient {
	return &dataProcessorClient{cc}
}

func (c *dataProcessorClient) Send(ctx context.Context, in *DataObject, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/data.DataProcessor/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataProcessorClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/data.DataProcessor/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProcessorServer is the server API for DataProcessor service.
type DataProcessorServer interface {
	Send(context.Context, *DataObject) (*SendResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedDataProcessorServer can be embedded to have forward compatible implementations.
type UnimplementedDataProcessorServer struct {
}

func (*UnimplementedDataProcessorServer) Send(ctx context.Context, req *DataObject) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedDataProcessorServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterDataProcessorServer(s *grpc.Server, srv DataProcessorServer) {
	s.RegisterService(&_DataProcessor_serviceDesc, srv)
}

func _DataProcessor_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProcessorServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataProcessor/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProcessorServer).Send(ctx, req.(*DataObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataProcessor_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProcessorServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataProcessor/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProcessorServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataProcessor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.DataProcessor",
	HandlerType: (*DataProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _DataProcessor_Send_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DataProcessor_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data/protos/data.proto",
}
